### ISSUE TITLE
Graphical model viewer to render for xmi files exported from fidl models

### ISSUE THREAD

**Issue by GoogleCodeExporter** [franca/franca#134]
```
When I get any fidl files to export to XMI, I could not succeed any model 
viewer software to parse and render it graphically. I tried it with ArgoUML and 
Enterprise Architect demo version.

Please find attached fidl sample test file created and XMI file exported from 
it, and a log file from argoXML that contains the errors during importing it.

If you can help me to understand the issue or route me to a reference that I 
can read more to find out it.

If there is already a graphical model viewer to render from this files except 
the ones I tried, it will be also more than welcome. 

Best regards,
Ozgur Bulkan

```

Original issue reported on code.google.com by `obul...@gmail.com` on 12 Feb 2015 at 10:59

Attachments:
- [yamaica_test_new_1.fidl](https://storage.googleapis.com/google-code-attachments/franca/issue-134/comment-0/yamaica_test_new_1.fidl)
- [yamaica_test_new_1.xmi](https://storage.googleapis.com/google-code-attachments/franca/issue-134/comment-0/yamaica_test_new_1.xmi)
- [yamaica_test_argoxml.log](https://storage.googleapis.com/google-code-attachments/franca/issue-134/comment-0/yamaica_test_argoxml.log)

**Comment by kbirken** [comment]
Closing this discussion.
