### ISSUE TITLE
Test and improve doxygen filter.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [franca/franca#141]
```
With Franca 0.9.2, a command-line filter for doxygen has been implemented, 
which can be used to add *.fidl files to documentation generated by doxygen 
(see issue 9). However, this was only a first draft and has to be tested and 
maybe improved. These are the actual open topics:

- Check the mapping to doxygen via OMG-IDL. The transformation results should 
be reviewed by some experienced doxygen users.
- The build of the final standalone command-line filter used by doxygen has to 
be done manually, it is not automated yet.
```

Original issue reported on code.google.com by `klaus.birken@gmail.com` on 8 May 2015 at 8:19

**Comment by kbirken** [comment]
Commit 4a3fdb5 provides improved handling of Franca structured comments. Interfaces and type collections are now documented by doxygen properly using the new franca2idl trafo. Enumeration, struct and other types are now documented, too. This should provide much better results when integrating Franca IDL models to a doxygen documentation.

**Comment by kbirken** [comment]
The new features of this update include:
- Franca structured comments are handled properly now
  - comments are now also supported for enumerators, struct fields, etc.
  - @description content is transformed to normal comments in doxygen, other Franca tags (e.g. @author, @deprecated) are transformed to proper doxygen counterparts
- doxygen pages describing interfaces and type collections now have a remark connecting to the original Franca model element
- version numbers (major/minor) in Franca are transformed properly
- attributes are generated properly (incl. the readonly flag)

The version number of the command-line tool (jar file) is now 0.7.0.
