### ISSUE TITLE
Franca deployments do not handle escaped identifiers correctly

### ISSUE THREAD

**Issue by klausuhl-intel** [franca/franca#157]
It is totally legal to use keywords of the Franca deployment language like "interfaces", "methods", "instances", etc. as identifiers in a Franca IDL definition (e.g. as method argument names, struct members, etc.). If a Franca deployment has to define properties for these IDL elements you have to escape them because they are keywords in the deployment DSL. However, this is not correctly handled in Franca deployments.

The problem is that Xtext does not strip the escape character from the identifier name. Therefore, the Franca deployment code gets an identifier that is does not know (e.g. "^interfaces") but expects an identifier that it can never get (e.g. "interfaces"). As far as I have understood it this behavior of Xtext is intentional and one has to use a value converter to strip off the escape character when this is required.

Here is a small example that reproduces this problem (posted inline as I am unable to attach files to this defect):

----- Test.fidl start -----
package test

typeCollection TestTypeCollection {
	struct A {
		Int32 interfaces
	}
}

interface TestInterface {
	method testMethod {
		in {
			Int32 methods
		}
	}
}
----- Test.fidl end -----

----- TestSpec.fdepl start -----
specification TestSpec {
	for struct_fields {
		TestProperty: String;
	}
	for arguments {
		TestProperty: String;
	}
}
----- TestSpec.fdepl end -----

----- Test.fdepl start -----
import "TestSpec.fdepl"
import "Test.fidl"

define TestSpec for typeCollection test.TestTypeCollection {
	struct A {
		^interfaces {
			TestProperty = "TestValue"
		}
	}
}

define TestSpec for interface test.TestInterface {
	method testMethod {
		in {
			^methods {
				TestProperty = ""
			}
		}
	}
}
----- Test.fdepl end -----

**Comment by kbirken** [comment]
Fixed with commit c467fbd on branch develop.
