### ISSUE TITLE
No negative values for integer deployment definition values possible

### ISSUE THREAD

**Issue by redcatbear** [franca/franca#158]
# Situation
When trying to define a negative value for a deployment attribute that is defined as "Integer", negative values are rejected. The type "Integer" suggest that negative values should be allowed otherwise "UnsignedInteger" would be more clear.

# Expected behavior
Positive and negative integer values are accepted

# Actual behavior
Only positive values and zero are accepted

# Environment:
Franca Runtime 010.0.201507291433
Franca UI 010.0.201507291433
Eclipse JEE 4.5.0.20150621-1200
Ubuntu Linux 15.04, 64 bit

# Steps to reproduce
1. FIDL: define a "typedef Foobar"
2. FDEPL: in "specification" define "for typedefs { Code : Integer }"
3. FDEPL: "typedef Foobar { Code = -1 }"

**Comment by kbirken** [comment]
Commit b3dfe55 on branch develop now allows Integer properties in deployment models to have negative values. Closing ticket.

Remark: It might be required in future to introduce an "Unsigned" type or to allow the possibility to specify ranges for the Integer type in deployment (analog to the ranged Integer type in fidl models).
