### ISSUE TITLE
import of interface not working accross dependency hierarchy

### ISSUE THREAD

**Issue by mbathelt** [franca/franca#159]
If there are several Franca deployment definitions chained by import statements, the imports performed by previous Franca files seem to be ineffective.
This is the problem scenario:
- A.fidl - contains IDL
- deploy_interface_A.fdepl - imports A.fidl
- deploy_instance_A.fdepl - imports deploy_interface_A.fdepl and should also import A.fidl implicitly
# A.fidl:

> package test
>     interface A {
>         version { major 1 minor 0 }
>         method getX {}
>     }
# deploy_interface_A.fdepl

>    import "platform:/plugin/org.genivi.commonapi.someip/deployment/CommonAPI-SOMEIP_deployment_spec.fdepl"
> import "A.fidl"
> define org.genivi.commonapi.someip.deployment for interface test.A {
>     SomeIpServiceID = 1
>     method getX {
>         SomeIpMethodID = 1
>     }
> }
# deploy_instance_A.fdepl

> import "platform:/plugin/org.genivi.commonapi.someip/deployment/CommonAPI-SOMEIP_deployment_spec.fdepl"
> import "deploy_interface_A.fdepl"
> import "A.fidl" // _why is this import REQUIRED??? It should not be neccessary!_
> define org.genivi.commonapi.someip.deployment for provider A_Provider_Instance1
> {
>     instance test.A as Instance1
>     {
>         InstanceId = "Instance 1"
>         SomeIpInstanceID = 1
>         SomeIpUnicastAddress = "1.2.3.4"
>         SomeIpReliableUnicastPort = 0
>         SomeIpUnreliableUnicastPort = 0
>     }
> }

sorry for copying the Franca files here, I could not find a way to attach them.

**Comment by mbathelt** [comment]
import "A.fidl" should be optional in "deploy_instance_A.fdepl", but it isn´t in Franca 0.9.1

**Comment by kbirken** [comment]
This basically means that import-statements should be transitive in deployment models. This is indeed not the case. Actually, import-statements in Franca IDL are not transitive, neither. In both DSLs, the import statements allow to access the model elements from the imported files, not from those imported by the imported files recursively.

The transitivity could be implemented. However, this would not scale for larger models. See the following comment by someone who did this in a production context: https://www.eclipse.org/forums/index.php?t=msg&th=508119&goto=1092057&#msg_1092057

Thus, I would like to avoid adding transitivity to import-statements in Franca. Please comment.

**Comment by kbirken** [comment]
No comment since two years, closing.
