### ISSUE TITLE
Redirecting output (don't use hardcoded System.out)

### ISSUE THREAD

**Issue by ckulla** [franca/franca#161]
We want to run the Franca to D-Bus Converter in a background daemon where the console output is redirected to a socket connection. Currently the class DBusConnector.java make use of System.out without giving us the chance to redirect the console output to another stream. Please extend the API so we can direct the output to another stream. 

A first workaround could be just changing System.out (e.g. System.out = mystream). But the daemon shall serve many requests in a multi-threaded environment. This means we can not reassign System.out to a single PrintStream.

**Comment by kbirken** [comment]
Implemented by commit d887db6 on develop.
