### ISSUE TITLE
Franca Examples trigger warnings with Franca 0.10

### ISSUE THREAD

**Issue by gmacario** [franca/franca#164]
Hello,

Trying to get my hands dirty with Franca 0.10 I have loaded project org.franca.examples.basic inside Eclipse and noticed that a few warnings are shown.

Please see [screenshot](https://genivi-oss.atlassian.net/wiki/download/attachments/5833028/Capture-20150925-1553.PNG?version=1&modificationDate=1443189242615&api=v2).

I believe I have a easy fix for at least 8 of them:

> Deprecated order of interface elements (contract should be at the end)

I may submit a Pull Request if you like...

Hope that helps,
Gianpaolo

**Comment by kbirken** [comment]
Removed most warnings in the two example projects (basic and deploy). Implemented by commit 67a770c and two previous commits on branch develop.

In the basic example, one warnings remains (this is done deliberately, because it shows the validation of interface contracts).

**Comment by kbirken** [comment]
I just updated the example project zip archive for the 0.10.0 version of Franca. It can be downloaded from the usual Google Drive folder.

https://drive.google.com/folderview?id=0B7JseVbR6jvhfm42djAxdVBZUFpoakdKazA3b0xLWjd6RHRNMUFDcDRNWDc1S200UTh0Q1k&usp=sharing

**Comment by gmacario** [comment]
Hi @kbirken,

Thanks for doing that.

By the way: Is there any reason why org.franca.examples.* are not delivered inside the FRANCA_UPDATE_SITE (i.e. https://franca.github.io/franca/update_site/releases/...) as all the other Franca features/plugins?

See https://github.com/gunnarx/franca_install_automation/blob/master/CONFIG

**Comment by kbirken** [comment]
@gmacario The reason it's not included in the update site is that the user does not want to install the example projects in the IDE, but wants to import it into the workspace instead and play around. 

Actually, there is a way in Eclipse to provide example projects via the "New project" wizard... but I never regarded importing a separate zip-file as inhibitory inconvenient...
