### ISSUE TITLE
France enumeration does not support hex definitions

### ISSUE THREAD

**Issue by mfhdev** [franca/franca#167]
Hi,

is there any possbility for Franca to support Hex definitions? The following currently fails: 

    enumeration eBitmask
    {    
        eBitmask_Value1 = 0x0000   
        eBitmask_Value2 = 0x0001   
        eBitmask_Value3 = 0x0002   
        eBitmask_Value4 = 0x0004   
        eBitmask_Value5 = 0x0008
    }

Can you add support for this? (As a workaround I can define decimal equivalents the but it's ugly)

**Comment by kbirken** [comment]
This is supported since Franca 0.10.0. See issue #92 for a detailed history. Actually, for defining values of enumerators any expression of integer type may be used (e.g., "0x1000 + 0x10" or "SOME_CONST + 0xff").
