### ISSUE TITLE
Method error statements can not have structured comment

### ISSUE THREAD

**Issue by mbathelt** [franca/franca#168]
A method with an error parameter can not be commented with a structured comment.
One could expect that the following IDL fragment works:
method getX {
        out {
            <**
                @description : nice result from this method.
            **>
            Int32 result
        }
        <**
                @description : ugly errors occurring in this method.
        **>
        error t.Errors
}

currently such IDL does not validate with the comment near "error".
This is bad as yamaica-ea uses structured comments for transformation an cannot exchange any documentation about error cases at this place.

**Comment by kbirken** [comment]
Fixed with commit b2f409d on branch develop.
