### ISSUE TITLE
Cannot Install KIELER Nightly.

### ISSUE THREAD

**Issue by gmalmeida** [franca/franca#169]
Hi there, 
I am just new to Franca and while following the instructions below available at: https://code.google.com/a/eclipselabs.org/p/franca/wiki/FrancaQuickInstallGuide:

> For the Franca UI Add-ons: Install the KIELER Lightweight Diagrams - Developer Resources & Examples feature of the KIELER open-source framework. Select Help > Install new software... and choose the following update site: KIELER Nightly. Note: Installing the Add-ons feature of older Franca versions (0.9.1 or earlier) requires a different installation, see section Installing older versions below.

I get the following error:

![kieler_layout_error_eclipse](https://cloud.githubusercontent.com/assets/5320909/10429578/e4a5c07c-70f9-11e5-9eca-e0c2153bdaa8.png)

URL used to add software: 
http://rtsys.informatik.uni-kiel.de/~kieler/updatesite/nightly

Appreciate your help.

**Comment by kbirken** [comment]
Please try to only install one feature: "KIELER Lightweight Diagrams - Developer Resources & Examples". In your screenshot, you checked all available features, which is too much :-)

**Comment by gmalmeida** [comment]
:joy: :joy: :joy: Thanks @kbirken :+1:
