### ISSUE TITLE
External deployment validators

### ISSUE THREAD

**Issue by MarkusHeiling** [franca/franca#171]
It would be great if there is a possibility, to add external validators for Franca deployment models, similar to the already existing for external validators for Franca IDL models ("org.franca.core.dsl.francaValidator"). This way the external validators for deployment models would integrate into the XText validation as part of the already existing Franca Deployment validator "org.franca.deploymodel.dsl.validation.FDeployJavaValidator".

**Comment by kbirken** [comment]
Good idea, thanks for reporting this! 

Implemented with commit 75230b6 on branch develop.
