### ISSUE TITLE
Fix issues with org.franca.examples.basic

### ISSUE THREAD

**Issue by gmalmeida** [franca/franca#172]
Hi there...

while trying to run some examples (i.e. `Franca2HtmlTest.java`), I get some import errors from Eclipse...

Please see attachment.

![franca_eclipse_demos](https://cloud.githubusercontent.com/assets/5320909/10638629/30e90ffc-780c-11e5-8989-6deee88dccfe.png)

Please let me know what I am doing wrong.

Thanks
Gabriel

Additionally I think the UserGuide 0.9.2.0 needs update:

> The example project will be part of your Eclipse workspace now. Open the Franca IDL
> example le examples/franca/demo1.dl

This file is not found in the package examples download from google drive (`org_franca_examples_src_2015-07-29.zip`).

**Comment by kbirken** [comment]
The screenshot looks like you didn't install Xtend in your IDE. The example HppGenerator is implemented using Xtend (xtend-language.org). If Xtend is installed, it will translate all *.xtend files into Java files in folder xtend-gen. It seems the folder is empty. 

You may try selecting the project in the package explorer and invoking menu item "Project > Clean" to trigger a rebuild. If Xtend is installed, it will create the Java file then.

**Comment by kbirken** [comment]
Regarding the remark about the docs, I will check and fix it if necessary.

**Comment by kbirken** [comment]
Updated user guide to fix the wrong filename reference.
