### ISSUE TITLE
Structured comments do not support "@" character

### ISSUE THREAD

**Issue by mbathelt** [franca/franca#173]
If someone wants to place e.g. a mail address in a structured Franca comment, this will fail due to collision with annotations.
Example Franca:
   <**
        @description : send any questions to someone@somewhere.com and hope for feedback
    **>

The validation fails in Franca 0.9.1 because it expects "@" to be used for annotations.

**Comment by mbathelt** [comment]
same problem occurs if "@" is replaced by "*":
   <**
@description : send any questions to someon*somewhere.com and hope for feedback
**>

**Comment by kbirken** [comment]
For this, we probably need to escape the @ character in the model files (like \@). See also similar issue #137.

**Comment by kbirken** [comment]
Implemented by commit 0480c29 on develop.

The '@' character can be used now in the annotation comment by escaping it with a backslash: \@
When accessing the comment string via the generated EMF API, the escape backslash will be removed.
