### ISSUE TITLE
Datatype "map" is not deployable

### ISSUE THREAD

**Issue by mbathelt** [franca/franca#174]
The Franca datatype "map" is generally missing in Franca deployment 0.10.
There is no way to specify any deployment attributes to a map´s key nor value in deployment specification, nor is it possible to refer to a map datatype in deployment definitions.
Franca deployment should be extended to support maps to enable consistent configurability for CommonAPI C++ SOME/IP protocol binding.

Example: In an IDL type collection we define:

```
map MyMap1 {
    String to Int64
}
```

In the deployment specification it should be possible to specify something like e.g.:

```
define org.genivi.commonapi.someip.deployment {
    for maps {
        MaxElements: Integer (default: 0)
    }
    for map_keys {
        MaxSize: Integer (default: 256)
    }

    for map_values {
        MaxValueCount: Integer (default:0)
    }
}
```

Of course it would also make sense to have map deployment definition specific as well as usage specific, i.e. have an expression like #map similar to #struct

**Comment by kbirken** [comment]
This feature is actually still missing in 0.11, should be added.

**Comment by mbathelt** [comment]
any solution for this problem underway?

**Comment by mbathelt** [comment]
is this ticket part of Franca 0.13 release?

**Comment by kbirken** [comment]
No, it didn't make it into 0.13.0.

**Comment by kbirken** [comment]
Pushed to develop.
