### ISSUE TITLE
FDeploy ecore models are not packaged

### ISSUE THREAD

**Issue by klausuhl-intel** [franca/franca#176]
The JAR file that is created while building the Franca deployment DSL plug-in does not contain the FDeploy.ecore and FDeploy.genmodel files. However, they are required when you want to integrate Franca deployment files into another Xtext based DSL.

**Comment by klausuhl-intel** [comment]
Pull request https://github.com/franca/franca/pull/177 should fix this issue.

**Comment by kbirken** [comment]
Pull request merged, will be part of release 0.11.0.
