### ISSUE TITLE
Lift Franca to Xtext/Xtend 2.8.

### ISSUE THREAD

**Issue by kbirken** [franca/franca#191]
Franca releases up to 0.10.0 are limited to Xtext/Xtend 2.7. We should update Franca 0.10.1 or later to Xtext/Xtend 2.8.4.

**Comment by rytina** [comment]
Why not lift it to 2.9?

**Comment by kbirken** [comment]
Some users have environments which are bound to earlier Franca versions. I want to provide at least one Franca release with Xtext 2.8, so that these users are able to get an update without being first to bump to Xtext 2.9. A follow-up Franca release based on Xtext 2.9 will be provided soon.

**Comment by rytina** [comment]
Super!

**Comment by kbirken** [comment]
Implemented by commit 1a7d94f (and earlier commits) on develop.
