### ISSUE TITLE
Please update info on compatibility with CommonAPI C++ > 3.1.5

### ISSUE THREAD

**Issue by gmacario** [franca/franca#203]
Hello Klaus,

During the last GENIVI SAT F2F we reviewed the <https://github.com/franca/franca/wiki/Compatibility-Overview>

This page details which version of Franca is compatible with which version of CommonAPI C++ (up to release 3.1.5).

As a matter of fact a few more releases of CommonAPI C++ are now available at

<https://github.com/GENIVI/capicxx-core-runtime> and related repositories

Would someone be able to update the wiki page at

<https://github.com/franca/franca/wiki/Compatibility-Overview>

listing which release of Franca is compatible with the most recent releases of CommonAPI C++ (latest is 3.1.10.1 as of 2016-12-12)?

Thank you very much

Gianpaolo Macario

**Comment by kbirken** [comment]
Updated the compatibility matrix as requested. Used information from Manfred Barthelt (from CommonAPI C++ team) that CommonAPI C++ 3.1.2 up to 3.1.10.1 is compatible with Franca 0.9.1.

**Comment by gmacario** [comment]
Thanks Klaus!
