### ISSUE TITLE
Please add documentation for type overwrites

### ISSUE THREAD

**Issue by moltob** [franca/franca#207]
I stumbled upon this in the grammar, then found related issue #133. As I am only sort of getting the implementing solution and how it is supposed to be used, please add this part to the documentation.

**Comment by kbirken** [comment]
Section 6.3.3 on deployment overwrites has been added in User Guide 0.12.0.1, which has been published recently. 

The User Guide 0.12.0.1 is available here: https://drive.google.com/drive/folders/0B7JseVbR6jvhUnhLOUM5ZGxOOG8?usp=sharing
