### ISSUE TITLE
Add binary literals to fidl and fdepl

### ISSUE THREAD

**Issue by moltob** [franca/franca#208]
Please consider adding binary literals for integer constants, similar to the current hex literal support in fidl. When starting to use Franca in non I&K domains, binary representation will allow keeping interface and deployment constants much closer to corresponding specifications.

**Comment by kbirken** [comment]
Thanks for the suggestion! Both Franca IDL and deployment models support binary literals now (going to be released with 0.11.1).

**Comment by moltob** [comment]
Thanks a lot!
