### ISSUE TITLE
Maven fails on using Franca update site with empty '0.11.2' directory

### ISSUE THREAD

**Issue by MarkusHeiling** [franca/franca#220]
The Franca update site configuration file "http://franca.github.io/franca/update_site/releases/compositeContent.xml" basically contains references to the following sub directories:

```
...
  <children size='5'>
      <child location='0.9.0'/>
      <child location='0.9.1'/>
      <child location='0.10.0'/>
      <child location='0.11.0'/>
      <child location='0.11.2'/>
  </children>
...
```

I think the '0.11.2' entry is new and still points to an empty directory and this empty '0.11.2' directory causes Maven to fail on builds which are referencing this Franca update site via "http://franca.github.io/franca/update_site/releases".

**Comment by kbirken** [comment]
Thanks for reporting - a typo in the xml file. Should be "0.11.1" - fixed.
