### ISSUE TITLE
Support write-only attributes in Franca IDL

### ISSUE THREAD

**Issue by mbathelt** [franca/franca#225]
**Proposal**
Add a modifier "writeonly" for attributes to Franca. The modifier suppresses the generation of an attribute getter in downstream tools. Only a setter as accessor is generated in this case.
The generation of a notifier is not affected.

**Rationale**
Existing modelling of signals found in the data driven ecosystem and accessed from the service-oriented world uses the attribute pattern intensively. For a so-called "Sollwert" request a setter of an attribute is modeled based on the data type of the originating signal. Unfortunately no getter nor notifier are needed. Where subscription can be removed by the modifier "nosubscription", Franca does lack the possibility to suppress the getter. In SOME/IP a corresponding modifier, called WRITE_ONLY exists.

**Example**
`interface woa {
    attribute TypeX someSignalOfTypeX writeonly
}`

**Limitations**
The modifiers readonly and writeonly must not be combined.

**Comment by kbirken** [comment]
Proposals for different naming of `writeonly`:
- `subscriptionOnly` (but: this also seems to restrict writing the attribute)
- `noPolling`

**Comment by bhennlich** [comment]
I vote for `noRead`

**Comment by mbathelt** [comment]
Voting for `noRead`  or `noGet`.

**Comment by kbirken** [comment]
We will implement this feature with keyword `noRead`.

**Comment by kbirken** [comment]
Implemented no develop, will be merged to master for release 0.12.0.
