### ISSUE TITLE
Add StructuredComment content to the Element Hover 

### ISSUE THREAD

**Issue by GENIVIFRANCAPLUS** [franca/franca#236]
As an user of Franca editor it would ease my work, if the information of structured comments <** ... **> of the IDL elements are included in the hover of the elements.

By default the MultiLineCommentDocumentationProvider adds the standard comments /* ... */ to the hover. This should be enriched with the structured info content.

**Comment by bhennlich** [comment]
see https://github.com/GENIVI/franca_plus/blob/master/plugins/org.franca.compmodel.dsl.ui/src/org/franca/compmodel/dsl/ui/contentassist/FCompDocumentationProvider.xtend

**Comment by kbirken** [comment]
Pushed on develop, waiting for release.
