### ISSUE TITLE
noRead flag for attributes

### ISSUE THREAD

**Issue by bhennlich** [franca/franca#237]
#225 introduced the noRead flag, to suppress the creation of a getter accessor for attributes. Unfortunately it is "exclusive or" to the readOnly flag. The two flags should be independent from each other. So that both can be set.

**Comment by kbirken** [comment]
This restriction was an explicit requirement in the original request of #225. Here is the corresponding text in the description of #225:

> The modifiers readonly and writeonly must not be combined.

We easily can switch the logic in the next Franca release, but I want to avoid toggling it several times... can you please discuss with @mbathelt and come up with a rationale why it should be one way or another?

In my point of view, a combination would seem quite paradox: `noRead readonly`.

**Comment by mbathelt** [comment]
Sorry after our discussion i considered topic #225 as agreed and did not review the overall ticket description down to the bottom line - my fault.

The rationale for having both noRead and readonly at the same time is, that in vehicle networks, i.e. SOME/IP or CAN, there are all combinations of the following communication patterns around:

- subscription/event based:
attribute value is provided to subscribers whenever the sender provides an update (e.g. "on change"). In Franca lack of this feature can be expressed by attribute modifier "noSubscription".
- get value by request/response:
attribute value can be requested which results in a single response. In Franca lack of this feature can be expressed by attribute modifier "noRead".
- set value:
update an attribute´s value from remote. In Franca lack of this feature can be expressed by attribute modifier "readonly".

Franca 0.12.0 cannot express attributes with "noRead readonly" modifiers, which would end up in attributes only able to receive subscribed events, but cannot be set nor request values.

**Comment by mbathelt** [comment]
Sorry after our discussion I considered topic #225 as agreed and did not review the overall ticket description down to the bottom line - my fault.
The rationale for having both noRead and readonly at the same time is, that in vehicle networks, i.e. SOME/IP or CAN, there are all combinations of the following communication patterns around:
•	subscription/event based:
attribute value is provided to subscribers whenever the sender provides an update (e.g. "on change"). In Franca lack of this feature can be expressed by attribute modifier "noSubscription".
•	get value by request/response:
attribute value can be requested which results in a single response. In Franca lack of this feature can be expressed by attribute modifier "noRead".
•	set value:
update an attribute´s value from remote. In Franca lack of this feature can be expressed by attribute modifier "readonly".
Franca 0.12.0 cannot express attributes with "noRead readonly" modifiers, which would end up in attributes only able to receive subscribed events, but cannot be set nor request values.

In natural languages (as well as for non Franca experts) the existing Franca keywords together with the negative semantic is quite puzzling. noRead readonly actually makes no sense in natural language, while it actually translates to "neigther readable nor writable from remote (but still notifiable)".

**Comment by kbirken** [comment]
Added check for attributes where all three flags are set. As this combination would prohibit any read or write access (including update notifications), it makes no sense. Here is the error marker text:

`Inconsistent flags of attribute 'ControllerOperationState', 
 prohibiting any read or write access.`

**Comment by kbirken** [comment]
Pushed on develop, waiting for release of 0.13.0.
