### ISSUE TITLE
Structured Comment Formatter  adds lines each time executed

### ISSUE THREAD

**Issue by bhennlich** [franca/franca#241]
The formatter routine add for StructuredComments each time it is executed an additional line per comment.

e.g.: 
```
<**
@description: derived class 
**>
```

gets 

```
<**
@description: derived class 

**>
```

after the first formatter run and,

```
<**
@description: derived class 


**>
```

after the second run...

This clutters the code with unwanted new lines.

**Comment by bhennlich** [comment]
I think the problem is default white space insertion of the Xtext formatter and the Terminal rule used in FAnnotation. The formatter adds between FAnnotations adds per default 1 blank. But parser adds the additional newline to the FAnnotation.

**Comment by bhennlich** [comment]
See https://github.com/GENIVI/franca_plus/blob/master/plugins/org.franca.compmodel.dsl/src/org/franca/compmodel/dsl/formatting2/FCompFormatter.xtend.
def dispatch void format(FCAnnotation fCAnnotation, extension IFormattableDocument document) 
and def dispatch void format(FCAnnotationBlock fCAnnotationBlock, extension IFormattableDocument document) 
The key is to use priorities to control the formatting.

**Comment by kbirken** [comment]
Pushed on develop, waiting for release.
