### ISSUE TITLE
Warnings in Eclipse IDE with Franca about .fdepl (Some/IP). CommonAPI

### ISSUE THREAD

**Issue by Bidon15** [franca/franca#248]
An issue is in Eclipse with Franca. IDE is showing warnings in code written for .fdepl (Some/IP) with following message: "Imported resource could not be found."

Issue is repoducible both in latest Genivi SDE (13 ver. Orion Release-type) as well as plain Eclipse(latest version) with Franca plugins.

Generating fidl and fdepl through CLI is working, but how to fix the warnings in IDE?

![fdepl_error](https://user-images.githubusercontent.com/1822365/37832750-288e1afa-2eb2-11e8-8553-0658a041bd3e.png)

**Comment by kbirken** [comment]
This resource is provided by a plug-in provided as part of CommonAPI C++ SOME/IP. I.e., CommonAPI C++ SOME/IP Tools and (as a preliminary) CommonAPI C++ Core Tools have to be installed in your workspace. These will also provide the CommonAPI code generators. 

Here are some links: 

- update site for CommonAPI core tools: http://genivi.github.io/capicxx-core-tools/updatesite/
- update site for CommonAPI some-ip tools: http://genivi.github.io/capicxx-someip-tools/updatesite/

Hope this helps. I am keeping the issue open for a little while in case you like to feedback.

**Comment by Bidon15** [comment]
Thanks so much for such valuable information. It helped. 
Hope this resolved issue will help in the future for others.
