### ISSUE TITLE
Quickfix for Interface Deployment Generation (e.g. CommonAPI SOME/IP)

### ISSUE THREAD

**Issue by mbathelt** [franca/franca#258]
CommonAPI SOME/IP interface deployment essentially requires identifiers for each interface element, e.g. SomeIpMethodID, SomeIpEventID, SomeIpGetterID, SomeIpNotifierID, SomeIpSetterID, SomeIpEventGroups.
Those identifiers MUST be unique within the interface no matter which kind of interface element it is used for. When creating a new interface it is quite clumsy to manually provide those numbers throughout all of the interface elements. Unfortunately the generic Quickfix only provides "0" as default ID for all interface elements and does not really reduce manual effort.

A specific Quickfix should provide unique numbers for each new interface element automatically.

    SomeIpMethodID, SomeIpGetterID, SomeIpSetterID should start from "1".
    SomeIpNotifierIDs and SomeIpEventID, which should start from "0x8001" according to SOME/IP spec.
    SomeIpEventGroups for broadcasts should start from "1".

Already existing interface element IDs should not be changed.

**Proposal:**
Provide an Eclipse extension point in the core deployment to enable custom Quickfix.

**Comment by kbirken** [comment]
Pushed to develop.

**Comment by kbirken** [comment]
See example project `examples/org.franca.examples.extensions`  with the example extension class `ExampleDefaultValueProvider`. It shows:

- how to provide default values specific to deployment properties
- how to format integers as decimal, hexadecimal and binary
- how to create default values which are of group type
- how to compute default values based on the order of elements in the deployed interface

The example does not show how to restrict the specific behavior to certain deployment specifications, but this can also be done by using `root.spec`.
