### ISSUE TITLE
Upgrade to Eclipse Photon and Xtext/Xtend 2.14

### ISSUE THREAD

**Issue by kbirken** [franca/franca#270]
Since 0.12.0, Franca is on Eclipse Neon and Xtext/Xtend 2.11. This will be updated to the latest versions.

**Comment by kbirken** [comment]
Pushed to master.

**Comment by mbathelt** [comment]
Hi Klaus, any chance to proceed to Eclipse 2020-x with xtext?

**Comment by kbirken** [comment]
I will maybe try it and proceed if the effort is not too high...
