### ISSUE TITLE
Fix build on travis-ci

### ISSUE THREAD

**Issue by kbirken** [franca/franca#299]
The travis.yml file is outdated and should be fixed.

**Comment by kbirken** [comment]
Resolved by commits aa908372 and c0f4dcb7, pushed to master. Travis builds are passing.

**Comment by cdietrich** [comment]
@kbirken  as travis will be shut down end of this year we might need to transfer to travis.com or somewhere else

**Comment by kbirken** [comment]
Thanks for the hint. I supposed that the open-source jobs will be migrated automatically...?

**Comment by cdietrich** [comment]
am not sure about that
