### ISSUE TITLE
Please update the link to CommonAPI C++

### ISSUE THREAD

**Issue by micericewice** [franca/franca#303]
GENIVI is now changed to COVESA.
Could you please update the link
https://genivi.github.io/capicxx-core-tools/
to
https://github.com/COVESA/capicxx-core-tools

Thanks,

**Comment by kbirken** [comment]
Thanks for the hint. I fixed the link in the README and also added a remark regarding the GENIVI-2-COVESA transition. Did you see the outdated capicxx-link anywhere else in the repository? If no, pls. close the issue.

**Comment by kbirken** [comment]
Has been fixed a while ago, closing the issue.
