### ISSUE TITLE
Queries about Franca and related IDLs

### ISSUE THREAD

**Issue by LakshyAAAgrawal** [franca/franca#309]
Hey!

I am currently studying Interface Description Languages and came across Franca. Particularly, I am interested in IDLs that allow for specifying ordering constraints on sequence of API calls. As per my understanding, Franca is the only IDL that supports this through the Protocol State Machines feature. Could you please address the following questions:
1. Are there any other IDLs that support such a feature, that allows specifying expected order of API calls like PSM?
2. Could anyone provide me with examples of projects that use Franca? Ideally, I would like to look into how other projects are using Franca, so I would be grateful if you could suggest something apart from the examples.
3. Is there any way to convert Franca PSMs to any other IDL?

**Comment by kbirken** [comment]
Hi, thanks for reaching out. Pls. find some responses below.

> I am currently studying Interface Description Languages and came across Franca. Particularly, I am interested in IDLs that allow for specifying ordering constraints on sequence of API calls. As per my understanding, Franca is the only IDL that supports this through the Protocol State Machines feature. Could you please address the following questions:
> 
> 1. Are there any other IDLs that support such a feature, that allows specifying expected order of API calls like PSM?

Yes, I don't know any other IDLs providing this feature. 

> 2. Could anyone provide me with examples of projects that use Franca? Ideally, I would like to look into how other projects are using Franca, so I would be grateful if you could suggest something apart from the examples.

Actually, many Automotive companies were using Franca over the past 10 years, and it is being used still by many. There is no complete list, as Franca is open-source and we cannot find out who is actually using it. But regarding from questions and private messages there are still many users. The main users are from car manufacturers (OEMs) and tier-1 suppliers. 

Additionally, there are some non-Automotive users. 

> 3. Is there any way to convert Franca PSMs to any other IDL?

As there is no other IDL supporting this, there is no model transformation available supporting this. But there is a series of [three blogposts](https://blogs.itemis.com/en/contract-based-software-development-with-franca) which we wrote with our partner Elektrobit, about benefits of using protocol state machines for interface definitions. 

Unfortunately, although many think that this feature is beneficial and could improve the system integration for complex technical systems a lot, it is rarely used in practice. Maybe the formal definition of the interface protocol is too unusual or too tedious.

**Comment by LakshyAAAgrawal** [comment]
Dear @kbirken, 

Thanks a lot for the response!

> Actually, many Automotive companies were using Franca over the past 10 years, and it is being used still by many. There is no complete list, as Franca is open-source and we cannot find out who is actually using it. But regarding from questions and private messages there are still many users. The main users are from car manufacturers (OEMs) and tier-1 suppliers.

> Additionally, there are some non-Automotive users.

I understand from this that most of the users are in proprietary settings. I request, that if anybody knows of at least 1 source code repository that uses Franca and is available publicly, I would be very grateful. I am mainly looking for few examples of software projects, that use semantic constraints similar to Protocol State Machines - Any semantic specification, that constrain the orders of API calls that can be made.

**Comment by kbirken** [comment]
As the last comment on this ticket was one month ago, I will close it as "won't fix". The purpose of the ticket is an investigation about Franca contracts, and not a request to fix a bug or add a feature to the repository.
